### ISSUE TITLE
Write CoC

### ISSUE THREAD

**Issue by laszlof** [franksworld/phpdetroit.io#11]
We need a conference code of conduct written

**Comment by adrian-enspired** [comment]
http://opensourcebridge.org/about/code-of-conduct/ (based on https://2015.belgrade.wordcamp.org/code-of-conduct/)

?

**Comment by laszlof** [comment]
I think displaying this, we could have a scrollable modal window. It may not need to be in the top menu in that case.

**Comment by adrian-enspired** [comment]
need contact info (e.g., email address) for the conference

**Comment by laszlof** [comment]
frank at php detroit dot io
