### ISSUE TITLE
CSP Problems

### ISSUE THREAD

**Issue by adrian-enspired** [franksworld/phpdetroit.io#22]
> Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…5oaWRlLmVuZCA9PT0gJ2Z1bmN0aW9uJyApIHsKCQlkbC5oaWRlLmVuZCgpOwoJfQp9KSgpOw==' because it violates the following Content Security Policy directive: "script-src https: 'unsafe-inline' 'unsafe-eval' ".

seems to be a font loader for "Benton Sans"

**Comment by laszlof** [comment]
Where are you seeing this at? That font isnt used as far as I can tell.

**Comment by adrian-enspired** [comment]
i don't see this anymore. may have been transient/unrelated.  we'll see if it comes back.
