### ISSUE TITLE
Mention full date range (July 27-29) at the top of the home page

### ISSUE THREAD

**Issue by iansltx** [franksworld/phpdetroit.io#95]
Looked around for a minute but wasn't sure exactly where to edit the JS templates to do that, but was figuring that switching

THURSDAY, JULY 26TH, 2018 / LIVONIA, MICHIGAN

to

THURSDAY-SATURDAY, JULY 26-28, 2018 / LIVONIA, MICHIGAN

Would provide a bit more useful information (including showing, at a glance, that it's a 3-day event in contrast to the 2-day ones elsewhere this year (Southeast and Cascadia).

**Comment by laszlof** [comment]
Thanks Ian, will get this fixed up in the AM.
